/* EasyCompiler.java */
/* Generated By:JavaCC: Do not edit this line. EasyCompiler.java */
import java.io.FileInputStream;
import java.io.FileNotFoundException;
public class EasyCompiler implements EasyCompilerConstants {
  public static void main(String args[]) {
    try {
          // Verificamos que al ejecutar envíen el nombre del archivo
          if (args.length == 0) {
            System.out.println("Error: Debes especificar un archivo. Ejemplo: java EasyCompiler codigo1.txt");
            return;
          }

          // Abrimos el archivo de texto
          FileInputStream archivo = new FileInputStream(args[0]);
          EasyCompiler compilador = new EasyCompiler(archivo);

          System.out.println("=== Iniciando analisis lexico de: " + args[0] + " ===");

          // Le pedimos el primer token
          Token token = compilador.getNextToken();

          // Ciclo que se repite hasta llegar al final del archivo (EOF)
          while (token.kind != EasyCompilerConstants.EOF) {

            // Atrapamos TODOS los tokens trampa definidos en tu manual
            if (token.kind == EasyCompilerConstants.ERROR_IDENTIFICADOR_INVALIDO) {
                System.out.println("Error lexico en linea " + token.beginLine + ", columna " + token.beginColumn);
                System.out.println("Detalle: Identificador no valido '" + token.image + "'");
                System.out.println("Consejo: Toda variable debe comenzar con una letra mayuscula y no con numeros.\n");
            }
            else if (token.kind == EasyCompilerConstants.ERROR_TEXTO) {
                System.out.println("Error lexico en linea " + token.beginLine + ", columna " + token.beginColumn);
                System.out.println("Detalle: Cadena de texto sin cerrar.");
            }
            else if (token.kind == EasyCompilerConstants.ERROR_CARACTER) {
                System.out.println("Error lexico en linea " + token.beginLine + ", columna " + token.beginColumn);
                System.out.println("Detalle: Caracter sin cerrar con comillas simples.");
            }
            else if (token.kind == EasyCompilerConstants.ERROR_NUMERO_INVALIDO) {
                System.out.println("Error lexico en linea " + token.beginLine + ", columna " + token.beginColumn);
                System.out.println("Detalle: Formato de numero decimal invalido '" + token.image + "'");
            }
            else if (token.kind == EasyCompilerConstants.ERROR_SIMBOLO) {
                System.out.println("Error lexico en linea " + token.beginLine + ", columna " + token.beginColumn);
                System.out.println("Detalle: Simbolo no valido '" + token.image + "' en el lenguaje.");
            }
            else {
                // Si es un token valido, lo imprimimos
                System.out.println("Linea " + token.beginLine + " | Token leido: " + token.image);
            }

            // Avanzamos al siguiente token
            token = compilador.getNextToken();
          }

          System.out.println("=== Analisis lexico finalizado ===");

        } catch (FileNotFoundException e) {
          System.out.println("El archivo " + args[0] + " no existe en la carpeta.");
        } catch (TokenMgrError e) {
          // Si el usuario escribe un símbolo rarísimo que no definiste en ningún lado
          System.out.println("Error critico del analizador: " + e.getMessage());
        }
  }

  /** Generated Token Manager. */
  public EasyCompilerTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private int jj_gen;
  final private int[] jj_la1 = new int[0];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
	   jj_la1_init_0();
	   jj_la1_init_1();
	}
	private static void jj_la1_init_0() {
	   jj_la1_0 = new int[] {};
	}
	private static void jj_la1_init_1() {
	   jj_la1_1 = new int[] {};
	}

  /** Constructor with InputStream. */
  public EasyCompiler(java.io.InputStream stream) {
	  this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public EasyCompiler(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source = new EasyCompilerTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
	  ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 0; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public EasyCompiler(java.io.Reader stream) {
	 jj_input_stream = new SimpleCharStream(stream, 1, 1);
	 token_source = new EasyCompilerTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
	if (jj_input_stream == null) {
	   jj_input_stream = new SimpleCharStream(stream, 1, 1);
	} else {
	   jj_input_stream.ReInit(stream, 1, 1);
	}
	if (token_source == null) {
 token_source = new EasyCompilerTokenManager(jj_input_stream);
	}

	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
  }

  /** Constructor with generated Token Manager. */
  public EasyCompiler(EasyCompilerTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
  }

  /** Reinitialise. */
  public void ReInit(EasyCompilerTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
  }

  private Token jj_consume_token(int kind) throws ParseException {
	 Token oldToken;
	 if ((oldToken = token).next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 if (token.kind == kind) {
	   jj_gen++;
	   return token;
	 }
	 token = oldToken;
	 jj_kind = kind;
	 throw generateParseException();
  }


/** Get the next Token. */
  final public Token getNextToken() {
	 if (token.next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 jj_gen++;
	 return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
	 Token t = token;
	 for (int i = 0; i < index; i++) {
	   if (t.next != null) t = t.next;
	   else t = t.next = token_source.getNextToken();
	 }
	 return t;
  }

  private int jj_ntk_f() {
	 if ((jj_nt=token.next) == null)
	   return (jj_ntk = (token.next=token_source.getNextToken()).kind);
	 else
	   return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;

  /** Generate ParseException. */
  public ParseException generateParseException() {
	 jj_expentries.clear();
	 boolean[] la1tokens = new boolean[54];
	 if (jj_kind >= 0) {
	   la1tokens[jj_kind] = true;
	   jj_kind = -1;
	 }
	 for (int i = 0; i < 0; i++) {
	   if (jj_la1[i] == jj_gen) {
		 for (int j = 0; j < 32; j++) {
		   if ((jj_la1_0[i] & (1<<j)) != 0) {
			 la1tokens[j] = true;
		   }
		   if ((jj_la1_1[i] & (1<<j)) != 0) {
			 la1tokens[32+j] = true;
		   }
		 }
	   }
	 }
	 for (int i = 0; i < 54; i++) {
	   if (la1tokens[i]) {
		 jj_expentry = new int[1];
		 jj_expentry[0] = i;
		 jj_expentries.add(jj_expentry);
	   }
	 }
	 int[][] exptokseq = new int[jj_expentries.size()][];
	 for (int i = 0; i < jj_expentries.size(); i++) {
	   exptokseq[i] = jj_expentries.get(i);
	 }
	 return new ParseException(token, exptokseq, tokenImage);
  }

  private boolean trace_enabled;

/** Trace enabled. */
  final public boolean trace_enabled() {
	 return trace_enabled;
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

}
