/* Generated By:JavaCC: Do not edit this line. EasyCompilerConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface EasyCompilerConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMENTARIO_LINEA = 5;
  /** RegularExpression Id. */
  int COMENTARIO_BLOQUE = 6;
  /** RegularExpression Id. */
  int INICIO = 7;
  /** RegularExpression Id. */
  int FIN = 8;
  /** RegularExpression Id. */
  int ENTERO = 9;
  /** RegularExpression Id. */
  int DECIMAL = 10;
  /** RegularExpression Id. */
  int BOOLEANO = 11;
  /** RegularExpression Id. */
  int CARACTER = 12;
  /** RegularExpression Id. */
  int TEXTO = 13;
  /** RegularExpression Id. */
  int SI = 14;
  /** RegularExpression Id. */
  int CONTRARIO = 15;
  /** RegularExpression Id. */
  int SINO = 16;
  /** RegularExpression Id. */
  int PARA = 17;
  /** RegularExpression Id. */
  int MIENTRAS = 18;
  /** RegularExpression Id. */
  int LEER = 19;
  /** RegularExpression Id. */
  int IMPRIMIR = 20;
  /** RegularExpression Id. */
  int INCREMENTO = 21;
  /** RegularExpression Id. */
  int DECREMENTO = 22;
  /** RegularExpression Id. */
  int SUMA = 23;
  /** RegularExpression Id. */
  int RESTA = 24;
  /** RegularExpression Id. */
  int MULTIPLICACION = 25;
  /** RegularExpression Id. */
  int DIVISION = 26;
  /** RegularExpression Id. */
  int MODULO = 27;
  /** RegularExpression Id. */
  int EXPONENTE = 28;
  /** RegularExpression Id. */
  int IGUAL_ASIGNACION = 29;
  /** RegularExpression Id. */
  int IGUAL_COMPARACION = 30;
  /** RegularExpression Id. */
  int DIFERENTE = 31;
  /** RegularExpression Id. */
  int MENOR = 32;
  /** RegularExpression Id. */
  int MENOR_IGUAL = 33;
  /** RegularExpression Id. */
  int MAYOR = 34;
  /** RegularExpression Id. */
  int MAYOR_IGUAL = 35;
  /** RegularExpression Id. */
  int Y_LOGICO = 36;
  /** RegularExpression Id. */
  int O_LOGICO = 37;
  /** RegularExpression Id. */
  int NO_LOGICO = 38;
  /** RegularExpression Id. */
  int ABRIR_LLAVE = 39;
  /** RegularExpression Id. */
  int CERRAR_LLAVE = 40;
  /** RegularExpression Id. */
  int ABRIR_PARENTESIS = 41;
  /** RegularExpression Id. */
  int CERRAR_PARENTESIS = 42;
  /** RegularExpression Id. */
  int PUNTO_COMA = 43;
  /** RegularExpression Id. */
  int VARIABLE = 44;
  /** RegularExpression Id. */
  int CONSTANTE = 45;
  /** RegularExpression Id. */
  int NUM_ENTERO = 46;
  /** RegularExpression Id. */
  int NUM_DECIMAL = 47;
  /** RegularExpression Id. */
  int CADENA = 48;
  /** RegularExpression Id. */
  int ERROR_TEXTO = 49;
  /** RegularExpression Id. */
  int ERROR_CARACTER = 50;
  /** RegularExpression Id. */
  int ERROR_NUMERO_INVALIDO = 51;
  /** RegularExpression Id. */
  int ERROR_IDENTIFICADOR_INVALIDO = 52;
  /** RegularExpression Id. */
  int ERROR_SIMBOLO = 53;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<COMENTARIO_LINEA>",
    "<COMENTARIO_BLOQUE>",
    "\"INICIO\"",
    "\"FIN\"",
    "\"ENT\"",
    "\"DEC\"",
    "\"BOOL\"",
    "\"LETRA\"",
    "\"TXT\"",
    "\"SI\"",
    "\"CONTRARIO\"",
    "\"SINO\"",
    "\"PARA\"",
    "\"MIENTRAS\"",
    "\"LEER\"",
    "\"IMPRIMIR\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"**\"",
    "\"=\"",
    "\"==\"",
    "\"!=\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"&&\"",
    "\"||\"",
    "\"!\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\";\"",
    "<VARIABLE>",
    "<CONSTANTE>",
    "<NUM_ENTERO>",
    "<NUM_DECIMAL>",
    "<CADENA>",
    "<ERROR_TEXTO>",
    "<ERROR_CARACTER>",
    "<ERROR_NUMERO_INVALIDO>",
    "<ERROR_IDENTIFICADOR_INVALIDO>",
    "<ERROR_SIMBOLO>",
  };

}
